Enabled shared library building on Linux.
open-quantum-safe/openssl pull request #117
Opened 2019-09-17 19:31 UTC by xvzcf

Making this a draft until I add CI tests.

2019-09-18 23:03 UTC, dstebila commented on fuzz/oids.txt
> +OBJ_oqsdefault="\x2B\xCE\x0F\x01\x01"
Do these need to be generated from templates? Or are we just putting a few in here as potentially tests but not necessarily the whole suite?

2019-09-18 23:04 UTC, dstebila commented on util/libcrypto.num
> +EVP_MD_CTX_copy_ex                      1016	1_1_0	NOEXIST::FUNCTION:
Is this related to some change we made?  Or a bug in upstream?

2019-09-19 18:22 UTC, xvzcf commented on fuzz/oids.txt
> +OBJ_oqsdefault="\x2B\xCE\x0F\x01\x01"
This file is autogenerated.

2019-09-19 18:22 UTC, xvzcf commented on util/libcrypto.num
> +EVP_MD_CTX_copy_ex                      1016	1_1_0	NOEXIST::FUNCTION:
I've fixed this and added a clarifying comment to the source.

2019-09-26 01:29 UTC, dstebila commented
What do we need to do to finish this off?

2019-09-26 14:40 UTC, xvzcf commented
Once [this](https://github.com/open-quantum-safe/openssl/pull/119) is merged in, I will add a template file that removes all the BIKE kems from the OpenSSL source only for the Debian shared build, which should hopefully do the trick.

2019-09-26 15:16 UTC, christianpaquin commented
Looks like the builds fail because they are looking for the old qtesla algs. Does the code need to be updated?

2019-09-26 15:17 UTC, xvzcf commented
Yes, I'm working on it right now.

2019-09-26 19:05 UTC, xvzcf commented
It turns out removing BIKE through templating is tricker than expected. I think we'll have to keep [this issue](https://github.com/open-quantum-safe/openssl/issues/116) open, and for now I'll be removing the debian-shared build job.

2019-09-26 20:39 UTC, christianpaquin requested changes

2019-09-26 20:39 UTC, christianpaquin commented on fuzz/oids.txt
> +OBJ_qteslaiiisize="\x2B\x06\x01\x04\x01\x82\x37\x59\x02\x02\x04"
These should be re-generated to use the new qTesla algs

2019-09-27 15:57 UTC, christianpaquin approved these changes

2019-09-27 16:03 UTC, christianpaquin commented
It would be good to be more descriptive in the README.md on explaining how to build with shared libs. Is it really that complicated to explain?

2019-09-27 19:04 UTC, xvzcf commented
It isn't, and I think a short note would do.

2019-09-27 19:11 UTC, merged