OQS-CMS
open-quantum-safe/openssl pull request #130
Opened 2019-11-15 13:49 UTC by baentsch

This 'activates' CMS sign-verify support for OQS algorithms. Digest is fixed to SHA512.

##### Checklist
- [x] documentation is added or updated
- [x] tests are added or updated

2019-11-19 21:04 UTC, dstebila requested changes

2019-11-19 21:04 UTC, dstebila commented on README.md
> +- Michael Baentsch (IBM Research Zurich)
Can you add some text earlier in the README.md about CMS being supported, and some examples on how to do that on the command-line, the examples corresponding to what you have in the test harness?

2019-11-19 21:04 UTC, dstebila commented on crypto/objects/obj_dat.h
> +    0x2B,0x06,0x01,0x04,0x01,0x82,0x37,0x59,0x02,0x02,0x0A,  /* [ 7839] OBJ_qteslapi */
Why have these changed?

2019-11-19 21:04 UTC, dstebila commented on oqs_test/scripts/do_openssl-cms.sh
> +diff result input
This script doesn't seem to ever have a non-success return code.

2019-11-20 06:33 UTC, zrlmib commented on oqs_test/scripts/do_openssl-cms.sh
> +diff result input
Well, it does: The result code is the result code of the concluding `diff` command: So if the verify operation doesn't (re)produce exactly the input file, the diff (and the test) fails.

2019-11-20 06:35 UTC, zrlmib commented on crypto/objects/obj_dat.h
> +    0x2B,0x06,0x01,0x04,0x01,0x82,0x37,0x59,0x02,0x02,0x0A,  /* [ 7839] OBJ_qteslapi */
`make generate_crypto_objects` changed these files after switching from `undef` (digest) to `sha512`. I decided to check these changes in such as to avoid having to add `make generate_crypto_objects` to all build scripts (which is a viable alternative).

2019-11-20 08:34 UTC, baentsch commented on README.md
> +- Michael Baentsch (IBM Research Zurich)
So done. Please review again.

2019-11-20 08:34 UTC, baentsch commented on crypto/objects/obj_dat.h
> +    0x2B,0x06,0x01,0x04,0x01,0x82,0x37,0x59,0x02,0x02,0x0A,  /* [ 7839] OBJ_qteslapi */
Result of `make generate_crypto_objects` after switching digests from `undef` to `sha512` as discussed.

2019-11-20 08:34 UTC, baentsch commented on oqs_test/scripts/do_openssl-cms.sh
> +diff result input
Comment added to code to explain it (-> result of diff defines outcome of test).

2019-11-20 16:07 UTC, christianpaquin requested changes
I added some comments after looking at the diffs. I'll next try running the code.

2019-11-20 16:07 UTC, christianpaquin commented on crypto/ec/oqs_meth.c
> +    X509_SIG_INFO_set(siginf, NID_sha512, NID_ALG, get_oqs_security_bits(NID_ALG),\
One thing that would be interesting would be to use the SHA function matching the security level of the NIST algorithm (SHA256 for L1, SHA384 for L2/L3, SHA512 for L4/L5) like we do in TLS auth pre-signing hashing (see the [pkey_oqs_digestsign](https://github.com/open-quantum-safe/openssl/blob/OQS-OpenSSL_1_1_1-stable/crypto/ec/oqs_meth.c#L964) function in oqs_meth.c).

2019-11-20 16:07 UTC, christianpaquin commented on RELEASE.md
> +- The OQS signature schemes are now also utilized to drive first parts of OpenSSL's CMS capabilities (e.g., to demonstrate quantum-safe code signing). An implementation of all [CMS](https://datatrack
what does "first parts" mean? I would explicitly list what is supported (and optionally what is not). We don't have to promise anything regarding the latter; it suffices to say what we have implemented.

2019-11-20 16:07 UTC, christianpaquin commented on crypto/objects/obj_dat.h
> +    1207,    /* OBJ_qteslapi                     1 3 6 1 4 1 311 89 2 2 10 */
The qtesla OIDs have been externally defined and shouldn't change.

2019-11-20 16:07 UTC, christianpaquin commented on crypto/objects/obj_xref.h
> +    {NID_oqsdefault, NID_sha512, NID_oqsdefault},
These were set as `NID_undef` following the integration strategy of `NID_ED25519`, which was OK for TLS. If the CMS code requires this to be set, then we should think about that a bit more. Following my earlier comment, I think this should be set to the SHA variant matching the NIST algorithm security level (SHA256 for L1, SHA384 for L2/L3, SHA512 for L4/L5). I'll need to review the code to understand where and how these values are used.

2019-11-20 16:07 UTC, christianpaquin commented on include/openssl/obj_mac.h
> +#define OBJ_qteslapi            1L,3L,6L,1L,4L,1L,311L,89L,2L,2L,10L
Same comment as before, the qtesla OIDs shouldn't change.

2019-11-20 16:07 UTC, christianpaquin commented on include/openssl/opensslv.h
> +# define OPENSSL_VERSION_TEXT    "OpenSSL 1.1.1d  10 Sep 2019 w/OQS"
I'm not sure if we want to touch this, since we are not touching the version number. Any code uses that for something other than displaying it? If not, then this should perhaps be "Open Quantum Safe fork of ..."

2019-11-20 16:18 UTC, baentsch commented on RELEASE.md
> +- The OQS signature schemes are now also utilized to drive first parts of OpenSSL's CMS capabilities (e.g., to demonstrate quantum-safe code signing). An implementation of all [CMS](https://datatrack
Agree, when looking at this again, this is too much text/information. Sign & verify are supported (as written in the README.md).

2019-11-20 16:21 UTC, baentsch commented on crypto/ec/oqs_meth.c
> +    X509_SIG_INFO_set(siginf, NID_sha512, NID_ALG, get_oqs_security_bits(NID_ALG),\
I thought about it, but then realised that this would mean touching the template generat(or) (where these [different] digest types would need to be evaluated/written out at build time in order to fill in obj_xref.txt correctly). Suggestions how to facilitate that very welcome!

2019-11-20 16:28 UTC, baentsch commented on include/openssl/opensslv.h
> +# define OPENSSL_VERSION_TEXT    "OpenSSL 1.1.1d  10 Sep 2019 w/OQS"
No code uses -- just an aid to maintain sanity in the presence of 'plain' and 'OQS-enabled' OpenSSL versions, particularly when working with dynamic libraries. Open to any suggestions.

2019-11-20 16:34 UTC, baentsch commented on crypto/objects/obj_dat.h
> +    1207,    /* OBJ_qteslapi                     1 3 6 1 4 1 311 89 2 2 10 */
I completely agree: OIDs should remain as registered. I do not remember touching this file at all and assumed all changes were caused by running `make generate_crypto_objects` (after adding sha512 to obj_xref.txt). Let me see whether I can find the reason/mechanism causing this change (and avoid it).

2019-11-20 17:56 UTC, christianpaquin commented on README.md
> +- CMS support (sign & verify using any of the [supported quantum-safe signature algorithms](#authentication))
It would be helpful to add a CMS demo subsection in the README.md's [Running section](https://github.com/open-quantum-safe/openssl/blob/OQS-OpenSSL_1_1_1-stable/README.md#running)); just a quick overview on how to exercise the PQC CMS functionality.

2019-11-20 18:31 UTC, christianpaquin commented
@baentsch, are you planning to migrate some tests to this PR, like [this one](https://github.com/zrlmib/openssl/blob/OQS-OpenSSL_1_1_1-stable/oqs_test/scripts/do_openssl-cms.sh)?

2019-11-21 07:41 UTC, baentsch commented on include/openssl/obj_mac.h
> +#define OBJ_qteslapi            1L,3L,6L,1L,4L,1L,311L,89L,2L,2L,10L
Same response as above: This happens automatically on the current master of openssl when `make generate_crypto_objects` is run (as documented [in the Contributing wiki](https://github.com/open-quantum-safe/openssl/wiki/Contributing-Guide#adding-an-authentication-algorithm) ) and thus independently of this PR. What about the suggestion to add `make generate_crypto_objects` to the baseline test procedure to flush out such problems going forward?

2019-11-21 08:48 UTC, baentsch commented
@christianpaquin Thanks for the suggestions regarding documentation: These are now done and checked in. I'm unsure I understand your last comment, though: The CMS testing already is part of the PR and CircleCI already shows it as running (and passing). Please review things again and close out comments addressed (same request to @dstebila): Thanks in advance.

2020-02-03 00:17 UTC, dstebila commented
Replaced by #141

2020-02-03 00:17 UTC, closed without merging