Moved OQS KEX definitions to the crypto layer
open-quantum-safe/openssl pull request #133
Opened 2019-12-20 17:36 UTC by christianpaquin

Moved OQS KEX definitions from the ssl layer to the crypto layer. OpenSSL's internal NIDs are now automatically generated through the build system (defined in `crypto/objects/objects.txt` and generate by `make generate_crypto_objects`) and are distinct from the TLS curve/group IDs (still defined by our own code in the ssl layer, because we define special code points for these "curves").

These changes should allow 3rd party applications (such as OpenVPN) to use the oqs algs when looking them up by NID.
`
This is a draft request:
- Some new code needs to be integrated with templating framework

2020-01-03 18:47 UTC, christianpaquin commented
@xvzcf, could you check that my modifications to the templating files are ok?

2020-01-06 17:01 UTC, xvzcf commented
The templating changes look fine to me.

2020-01-22 02:15 UTC, dstebila requested changes

2020-01-22 02:15 UTC, dstebila commented on ssl/t1_lib.c
> +    /* } */
Can this code be deleted rather than just commented out?

2020-01-22 18:50 UTC, christianpaquin commented on ssl/t1_lib.c
> +    /* } */
Yes, I'll remove it.

2020-01-23 01:54 UTC, dstebila approved these changes

2020-01-23 01:54 UTC, merged