Increase max size for signatures in speed.c
open-quantum-safe/openssl pull request #178
Opened 2020-05-06 21:22 UTC by christianpaquin

Increases max signature sizes for speed tests to 35000 (enough for picnicl1fs). Test code is hard to read, but it uses the last value of `lengths_list` array to allocate the signature buffer in the OQS tests. We'll need to update this value as we add algs with larger sigs.

Fixes issue #159.

2020-05-07 04:53 UTC, baentsch requested changes
I'm dumbfounded. Thanks very much: It looks like this indeed fixes the error. A full speed run with this patch doesn't SIGSEGV any more. Something else with picnic must have changed, though, as the error couldn't be triggered any more (before applying this patch!) by running picnic alone (as was the case when I created the issue). Whatever, case closed!

Before merging, would you please remove the two references to `OPENSSL_NO_CLEANUP` to re-activate full testing (one in `apps/speed.c` and one in `oqs_test/scripts/do_openssl-speed.sh`)? Thanks in advance.

2020-05-07 14:31 UTC, christianpaquin commented
> Something else with picnic must have changed, though, as the error couldn't be triggered any more (before applying this patch!) by running picnic alone (as was the case when I created the issue). Whatever, case closed!

The speed tool crashed for me at different point on different machines (sometimes during signing, sometime during verification). Probably depends on the state of the heap, which could vary I suppose from machine to machine, debug vs. release, etc.

> Before merging, would you please remove the two references to `OPENSSL_NO_CLEANUP` to re-activate full testing (one in `apps/speed.c` and one in `oqs_test/scripts/do_openssl-speed.sh`)? 

Will do.

2020-05-07 14:38 UTC, christianpaquin commented
@baentsch, in `do_openssl-speed.sh`, shouldn't there be another return code check after running the sig tests, just like with the KEMs:

```
if [ $? -ne 0 ]; then
   exit -1
fi
```

2020-05-07 14:47 UTC, baentsch commented
@christianpaquin No, such code would not be necessary: The last command run provides the exit code for the whole script: If it fails, the script fails (and vice versa). But it also shouldn't hurt.

2020-05-12 08:50 UTC, baentsch approved these changes
do_openssl-speed.sh redone anyway.

2020-05-12 13:51 UTC, dstebila commented
> do_openssl-speed.sh redone anyway.

Currently Github is recording a conflict with do\_openssl-speed.sh.  Will someone be rebasing to resolve the conflict before merging?

2020-05-12 14:28 UTC, baentsch commented
Easiest in my eyes would be probably for @christianpaquin to just remove `do_openssl-speed.sh` completely from the PR (which I didn't suitably express in my obviously overly short comment above). Sorry for asking for this change in the first place (as it became unnecessary due to the testing overhaul).

2020-05-12 16:16 UTC, christianpaquin commented
Done.

2020-05-12 16:32 UTC, merged