Added BoringSSL interoperability tests.
open-quantum-safe/openssl pull request #198
Opened 2020-05-21 23:09 UTC by xvzcf

I've also added a new CircleCI job for BoringSSL interop-testing. Presently it's not a nightly-only job, but I'll change it to be nightly-only once the PR is approved.

I also haven't added a README for these tests, since I'm considering breaking them out into a separate "interoperability testing" repository once we're done with this release cycle.

2020-05-22 04:23 UTC, baentsch commented on .gitignore
> +/oqs-interop-test/bssl_algorithms.py
The file `bssl_algorithms.py` seems important for the test flow. Why is it in .gitignore?

2020-05-22 04:44 UTC, baentsch requested changes
I may not be the right reviewer as I don't know enough about BoringSSL -- but allow me to ask regardless: I didn't find CMS interop tests: Does it also have no capabilities (apparently like s2n) for this? But then I also didn't understand how plain certificate/keys are tested (picked up by BoringSSL, if it can't generate them) -- but _that_ must be possible, no? Or does BoringSSL have no notion of persistent PKI (data structures)? A README in the oqs-interop folder to explain the test strategy would be goodness "for posteriority" (or guys like me understanding not enough of the underlying assumptions & goals of the testing).

2020-05-22 04:44 UTC, baentsch commented on oqs-interop-test/test_basic.py
> +                                '-loop']
How is a BoringSSL server picking up the keys and certificates that OpenSSL is using? Maybe a comment here to explain?

2020-05-22 04:44 UTC, baentsch commented on oqs-interop-test/test_basic.py
> +                                                             '-groups', 'oqs_kem_default',
Why is (only) 'oqs_kem_default' hardcoded here? What's with the other KEMs?

2020-05-22 04:44 UTC, baentsch commented on oqs-interop-test/test_full.py
> +                                '-sig-alg', sig_alg,
Same question as before: How is certificate+key (file) picked up/interop tested?

2020-05-22 04:44 UTC, baentsch commented on oqs-scripts/build_liboqs.sh
> +#                    if 'noopenssl', build a static library without OpenSSL SHA/AES code.
Shouldn't shared/static and openssl/noopenssl be independent combinations? In other words, why would there be no reason to ever build shared+noopenssl (seems impossible with this)?

2020-05-22 13:42 UTC, xvzcf commented on .gitignore
> +/oqs-interop-test/bssl_algorithms.py
I've put it there since it is "auto-generated" [here](https://github.com/open-quantum-safe/openssl/pull/198/files#diff-787e2ee4e783740c5416aa62b3fa49dfR21). The file is picked up from the BoringSSL source code to determine what algorithms BoringSSL supports.

2020-05-22 13:45 UTC, xvzcf commented on oqs-interop-test/test_basic.py
> +                                '-loop']
The `bssl server` program generates a self-signed cert as seen [here](https://github.com/open-quantum-safe/boringssl/blob/master/tool/server.cc#L138). It also means I'm only generating self-signed certificates for these tests (as opposed to self-signed CA signing a server certificate).

2020-05-22 13:48 UTC, xvzcf commented on oqs-interop-test/test_basic.py
> +                                                             '-groups', 'oqs_kem_default',
The idea behind the "basic" tests, is to test all KEMS with the signature set to `oqs_sig_default`, and then test all signatures with the KEM set to `oqs_kem_default`. Not every possible combination of KEM+Signature is tested here; that's done in `test_full.py`. I've the basic tests in the code, but not the CI, to make for a faster testing+development cycle before opening a PR.

2020-05-22 13:49 UTC, xvzcf commented on oqs-scripts/build_liboqs.sh
> +#                    if 'noopenssl', build a static library without OpenSSL SHA/AES code.
You're right, will fix that.

2020-05-22 13:59 UTC, baentsch commented on oqs-interop-test/test_basic.py
> +                                '-loop']
OK... for a BoringSSL<->BoringSSL connection test I'd understand that, but shouldn't a BoringSSL<->OpenSSL connection test (also) validate "each other's" persistent data structures (aka certs)? How otherwise do we check server auth of the implementations against each other? Or is that out of scope? That said, do we have a scope for this testing written up somewhere?

2020-05-22 14:04 UTC, baentsch commented on .gitignore
> +/oqs-interop-test/bssl_algorithms.py
Where is that file "auto(matically) generated"? I thought this requires a manual execution of 'generate.py', no? We don't demand that for the other files generated from that script, do we? How does CI "get hold" of this file?

2020-05-22 14:05 UTC, baentsch commented on oqs-interop-test/test_basic.py
> +                                                             '-groups', 'oqs_kem_default',
Understood. Makes sense. Whatever remains of this in the code, I'd suggest to document in a README.md for interop tests.

2020-05-22 14:10 UTC, xvzcf commented on .gitignore
> +/oqs-interop-test/bssl_algorithms.py
No, not quite. It's done in [oqs-scripts/clone_boringssl.sh](https://github.com/open-quantum-safe/openssl/blob/interop-tests/oqs-scripts/clone_boringssl.sh#L21) when the OQS-BoringSSL source code is obtained.

2020-05-22 14:44 UTC, xvzcf commented on oqs-interop-test/test_basic.py
> +                                '-loop']
The scope hasn't been written anywhere, but I'll add it to a README in this directory. The objective (I assume) is to test simply whether OQS-BoringSSL can process OQS-OpenSSL certificates and vice versa.

The `expect-peer-signature-algorithm` and `-expect-peer-cert-file` options [here](https://github.com/open-quantum-safe/openssl/blob/interop-tests/oqs-interop-test/test_basic.py#L96) do just that. I'll look into whether I can use similar options with OpenSSL.

2020-05-22 15:52 UTC, xvzcf commented
>  I didn't find CMS interop tests: Does it also have no capabilities (apparently like s2n) for this?

Judging from the things tested [here](https://github.com/open-quantum-safe/boringssl/blob/master/crypto/pkcs7/pkcs7_test.cc), it seems BoringSSL supports PKCS7 insofar as it applies to certificates. It certainly does not have a full fledged tool like `openssl cms`, as seen [here](https://github.com/open-quantum-safe/boringssl/tree/master/tool).

2020-05-25 10:39 UTC, baentsch commented on .gitignore
> +/oqs-interop-test/bssl_algorithms.py
Ah, now I understand the logic: Thanks! The only caveat: This seems brittle: Do I get it right that --if anything changes in 'openssl/oqs-template/config.yml' _or_ in the NID assignment there (via `make generate_crypto_objects`), that the 'BoringSSL/oqs-template/config.yml' must be manually adapted (all NIDs checked!) and the script run again? No automation possible? Maybe create an issue to not forget about this?

2020-05-25 10:43 UTC, baentsch commented on oqs-interop-test/test_basic.py
> +                                '-loop']
Hmm -- wouldn't usage of the `bssl s_client -root-certs` option allow us to use exactly the same "test infrastructure" (and certs) we use in openssl?

2020-05-25 10:51 UTC, baentsch commented
> > I didn't find CMS interop tests: Does it also have no capabilities (apparently like s2n) for this?
> 
> Judging from the things tested [here](https://github.com/open-quantum-safe/boringssl/blob/master/crypto/pkcs7/pkcs7_test.cc), it seems BoringSSL supports PKCS7 insofar as it applies to certificates. It certainly does not have a full fledged tool like `openssl cms`, as seen [here](https://github.com/open-quantum-safe/boringssl/tree/master/tool).

OK - one thing less to test interop of :) But certs I'd argue we should check (or create an issue as to be something that should be tested).

2020-05-25 14:19 UTC, xvzcf commented on .gitignore
> +/oqs-interop-test/bssl_algorithms.py
`make generate_crypto_objects` should only affect OpenSSL-internal NIDs. What matters for interoperability are the TLS curve IDs, which have to be manually ensured to be the same in the `generate.yml` files for OpenSSL and BoringSSL. This does not mean all curve IDs should be checked, just the ones that changed.

I don't know if it is worth automating consistency checks between the two files. I don't expect the relevant fields there (such as OIDs and code-points) to change frequently and drastically.

2020-05-25 15:28 UTC, xvzcf commented on oqs-interop-test/test_basic.py
> +                                '-loop']
I use `bssl_shim` instead of `bssl s_client` because the options the shim supports (such as [expect-curve-id](https://github.com/open-quantum-safe/boringssl/blob/master/ssl/test/test_config.cc#L214)) makes for a more elegant way to test the TLS connection (as opposed to having to parse the output.)

That being said. I've [updated](https://github.com/open-quantum-safe/openssl/pull/198/commits/ebd0a4c20b4b54f805925b61e6afb648f1822ff0) the interoperability tests: `openssl s_server` now generates a root and a server certificate, and `bssl_shim` now checks for a certificate chain of length 2 through the `expect-peer-cert-file` option.

The other way round: `openssl s_client` talking to `bssl server`, still uses just one certificate.

2020-05-25 15:31 UTC, baentsch commented on oqs-interop-test/test_basic.py
> +                                '-loop']
Cool: Thanks!

2020-05-25 15:35 UTC, baentsch approved these changes

2020-05-25 17:59 UTC, merged