Added remaining signature algorithms and fixed bugs.
open-quantum-safe/openssl pull request #213
Opened 2020-06-17 21:18 UTC by xvzcf

Will squash commits before merging.

@christianpaquin can you confirm this PR works with OpenVPN?

2020-06-18 01:59 UTC, dstebila approved these changes

2020-06-18 01:59 UTC, dstebila commented on README.md
> -#### Windows
Why are we removing the Windows build instructions? I thought this worked.

2020-06-18 01:59 UTC, dstebila commented on README.md
> +**N.B.**: Only the L1 signature variants and `rainbowVcclassic` are enabled by default. Should you wish to enable additional variants, consult [the "Code Generation" section of the documentation in t
Can you move this paragraph up to line 97?

2020-06-18 02:03 UTC, dstebila commented
Also: update line 302 of README.md with the same list of companies in the liboqs README.md.

2020-06-18 06:23 UTC, baentsch commented on README.md
> +**N.B.**: Only the L1 signature variants and `rainbowVcclassic` are enabled by default. Should you wish to enable additional variants, consult [the "Code Generation" section of the documentation in t
@xvzcf I'm confused: Wasn't the statement yesterday that all sig-combinations can remain in as nothing breaks this way? The logic described above in my eyes is far from ideal: Do we really want to _remove completely_ from the standard build "interesting" signature combinations ("strong" PQ algorithm with "equivalent" classic algorithm)? 
And reading further into the changes: Do I read correctly in the PR that even plain, non-hybrid PQ sig algs get removed with this PR from the list of 'normally available' signature algorithms? I don't particularly like this. At the very least, I'd like to retain Dilithium3 over Dilithium2 (which security-wise is not really suitable anyway). But then again, strong Falcon also got removed -- and not just the hybrid... 
In general, my question is: What's the deciding factor as to which algorithms to keep by default enabled? If it's performance (?) I'm really unhappy with the default list in this PR. @christianpaquin @dstebila : What's your take on this?

2020-06-18 14:07 UTC, christianpaquin commented on README.md
> +**N.B.**: Only the L1 signature variants and `rainbowVcclassic` are enabled by default. Should you wish to enable additional variants, consult [the "Code Generation" section of the documentation in t
I don't understand either the logic of removing the algorithms. My understanding from the call yesterday was also that we can keep the existing algorithms as is. In particular, I'd like qtesla-p-iii and picnic2 to remain enabled by default.

2020-06-18 14:14 UTC, christianpaquin requested changes
This PR is quite massive, especially at a RC stage. I would have expected a simple addition of new algs, without removing existing ones (breaking the RC expectations).  Isn't that possible?

2020-06-18 14:14 UTC, christianpaquin commented on README.md
> -The steps below have been confirmed to work on macOS 10.14 (clang 10.0.0), Ubuntu 18.04.1 (gcc-7), and Windows 10 (VS2019 build tools).
Why removing this?

2020-06-18 18:33 UTC, xvzcf commented on README.md
> +**N.B.**: Only the L1 signature variants and `rainbowVcclassic` are enabled by default. Should you wish to enable additional variants, consult [the "Code Generation" section of the documentation in t
I apologize for the confusion. I reverted these changes, but if anyone's puzzled about why I made them in the first place, I could go over my thought process in a call.

2020-06-18 18:34 UTC, xvzcf commented on README.md
> -The steps below have been confirmed to work on macOS 10.14 (clang 10.0.0), Ubuntu 18.04.1 (gcc-7), and Windows 10 (VS2019 build tools).
I made this change before you tried to build it on Windows again, and I forgot to revert it. I've added the instructions back.

2020-06-18 20:31 UTC, xvzcf commented
> This PR is quite massive, especially at a RC stage. I would have expected a simple addition of new algs, without removing existing ones (breaking the RC expectations). Isn't that possible?

I've kept the existing ones in. The only difference is that some signature code points have changed (in order to keep everything sequential). If that causes problems with OpenVPN, I can revert those changes too.

2020-06-18 21:36 UTC, christianpaquin commented
> > This PR is quite massive, especially at a RC stage. I would have expected a simple addition of new algs, without removing existing ones (breaking the RC expectations). Isn't that possible?
> 
> I've kept the existing ones in. The only difference is that some signature code points have changed (in order to keep everything sequential). If that causes problems with OpenVPN, I can revert those changes too.

That should be ok; I'll ask for a re-test when we tag another RC.

2020-06-19 14:23 UTC, christianpaquin approved these changes

2020-06-19 15:21 UTC, merged