fix build error
open-quantum-safe/openssl pull request #220
Opened 2020-07-08 06:27 UTC by baentsch

This fixes the nightly build errors by adding `picnic3` instead of `picnic2`. 

OIDs have been counted up.

##### Checklist
- [x] documentation is added or updated
- [x] tests are added or updated (automatic)
CCI execution [here](https://app.circleci.com/pipelines/github/baentsch/openssl/90/workflows/0aaeef2c-e5a7-436c-a1b5-561173858783)

2020-07-08 13:51 UTC, christianpaquin submitted a review, later dismissed

2020-07-08 13:51 UTC, christianpaquin commented on crypto/objects/objects.txt
> +1 3 6 1 4 1 311 89 2 1 18 : picnic3l1 : picnic3l1
For the last element of the OID, I had reserved 0x for picnic, 1x for picnic2, and I would put 2x for picnic 3. Can you set the picnic3 OIDs to "1 3 6 1 4 1 311 89 2 1 21", "... 22", and "... 23"?

2020-07-08 14:48 UTC, baentsch commented on crypto/objects/objects.txt
> +1 3 6 1 4 1 311 89 2 1 18 : picnic3l1 : picnic3l1
So done. Please check again.

2020-07-08 14:49 UTC, baentsch commented on crypto/objects/objects.txt
> +1 3 6 1 4 1 311 89 2 1 18 : picnic3l1 : picnic3l1
For the avoidance of doubt: I won't merge this but suggest @xvzcf does when `openssl` release is done.

2020-07-14 23:04 UTC, dstebila requested changes
Can you rebase this off of master, and then undo #221 and #222 so it is no longer pinned to liboqs 0.3.0?  Once this passes with liboqs HEAD it should be ready to merge.

2020-07-15 05:33 UTC, baentsch commented
> Can you rebase this off of master, and then undo #221 and #222 so it is no longer pinned to liboqs 0.3.0? Once this passes with liboqs HEAD it should be ready to merge.

So done. Please re-review and approve for merge.

2020-07-15 13:06 UTC, dstebila approved these changes

2020-07-15 13:08 UTC, merged