Rainbow oids
open-quantum-safe/openssl pull request #271
Opened 2021-01-12 20:41 UTC by xvzcf

Will update OIDs in BoringSSL once we're set here.

2021-01-13 05:59 UTC, baentsch submitted a review, later dismissed
subject to BoringSSL updates to achieve interop again, looks good to me.

2021-01-18 18:45 UTC, dstebila commented on oqs-template/oqs-kem-info.md
> +| Family         | Variant         |   Claimed NIST Level | PQ-only Code Point   | Hybrid Elliptic Curve   | Hybrid Code Point   |
Compared to the Google Docs spreadsheet, this is missing several pieces of information:

- algorithm version / NIST Round
- old numbering
- the x25519 hybrids

2021-01-18 18:46 UTC, dstebila requested changes
Missing information in KEM table.

2021-02-12 17:50 UTC, xvzcf commented on oqs-template/oqs-kem-info.md
> +| Family         | Variant         |   Claimed NIST Level | PQ-only Code Point   | Hybrid Elliptic Curve   | Hybrid Code Point   |
@dstebila I added in the x25519 hybrids. Could you expand on what you mean by "old numbering"?

2021-02-12 18:07 UTC, dstebila commented on oqs-template/oqs-kem-info.md
> +| Family         | Variant         |   Claimed NIST Level | PQ-only Code Point   | Hybrid Elliptic Curve   | Hybrid Code Point   |
When an algorithm spec changes, we have been bumping the OIDs and other identifiers.  For example, since Dilithium round 3 is different from Dilithium round 2, the code points that we maintain for them should be bumped.

2021-02-12 18:18 UTC, xvzcf commented on oqs-template/oqs-kem-info.md
> +| Family         | Variant         |   Claimed NIST Level | PQ-only Code Point   | Hybrid Elliptic Curve   | Hybrid Code Point   |
Oh okay, this script just picks up whatever's in the `generate.yml` files, so that shouldn't be a problem as long as they're updated.

2021-02-12 20:54 UTC, xvzcf commented
I've added an implementation version column to the markdown files. This is through a new script `generate-oid-nid-table.py` that takes as argument a path to the liboqs `docs` directory. It then goes through all the KEM and signature documentation files and pulls out the version information to add to the table.  

Can this PR be considered for merging? Once those files are YAMLized I can open another PR to pull more information out.

2021-02-12 22:04 UTC, dstebila approved these changes

2021-02-16 07:29 UTC, baentsch requested changes
Don't fully understand generate-oid-nid-table.py. Interop tests also fail: Would updating boringssl first be a reasonable precondition for this PR?

2021-02-16 07:29 UTC, baentsch commented on oqs-template/generate-oid-nid-table.py
> +    if kem['name_group'] == 'kyber512':
Why are these algorithm-specific lines needed?

2021-02-16 14:59 UTC, xvzcf commented on oqs-template/generate-oid-nid-table.py
> +    if kem['name_group'] == 'kyber512':
The purpose of this script is to automate the production of the [KEM and signature TLS 1.3 identifier tables](https://docs.google.com/spreadsheets/d/12YarzaNv3XQNLnvDsWLlRKwtZFhRrDdWf36YlzwrPeg/edit?ts=5ed16908#gid=0). The KEM table there contains a few KEM+x25519 hybrid identifiers, which we do not have in `generate.yml`, which is why I added those algorithm-specific-lines.

And yes, I will update BoringSSL before merging this in.

2021-02-16 15:20 UTC, baentsch commented on oqs-template/generate-oid-nid-table.py
> +    if kem['name_group'] == 'kyber512':
>  The KEM table there contains a few KEM+x25519 hybrid identifiers, which we do not have in generate.yml

Now I'm wondering: What code implements those hybrids? I also didn't see any of this in [the README](https://github.com/open-quantum-safe/openssl/blob/OQS-OpenSSL_1_1_1-stable/README.md). Side note: When looking at the README -- do you know where all the asterisks did go?? We have enabled quite a few more algorithms than are labelled, no?

Thanks in advance for the Boring-update.

2021-02-16 15:25 UTC, baentsch commented on oqs-template/generate-oid-nid-table.py
> +    if kem['name_group'] == 'kyber512':
> do you know where all the asterisks did go?? We have enabled quite a few more algorithms than are labelled, no?

Answering myself: They need to be escaped to not change algorithm names to italics. Would you want to do that in this PR while you're at it or shall I do a separate PR?

2021-02-16 15:32 UTC, baentsch commented on oqs-template/generate-oid-nid-table.py
> +    if kem['name_group'] == 'kyber512':
FYI: Code change was trivial, works and for reference is [here](https://github.com/open-quantum-safe/openssl/tree/mb-escapeasterisks): I refrain from doing a PR as it would create collisions/rebasing for you with this PR.

2021-02-16 15:43 UTC, xvzcf commented on oqs-template/generate-oid-nid-table.py
> +    if kem['name_group'] == 'kyber512':
The x25519 hybrids are not implemented in the OQS forks of OpenSSL or BoringSSL. @dstebila might be able to expand on this.

As for escaping the asterisks, you could just push it to my branch, or I can do so in a bit.

2021-02-16 16:02 UTC, baentsch commented on oqs-template/generate-oid-nid-table.py
> +    if kem['name_group'] == 'kyber512':
> As for escaping the asterisks, you could just push it to my branch

Simple solution: Thanks. Done.

2021-02-16 16:09 UTC, baentsch commented on oqs-template/generate-oid-nid-table.py
> +    if kem['name_group'] == 'kyber512':
(Additional note: I stopped the unnecessary CI run right now -- also, please do run `python3 oqs-template/generate.py` before finalizing the PR. I didn't want to do that as you had some changes in README.md and want to leave it to you to judge whether they'd be "unduly impacted" -- shouldn't be, but I don't want to mess with your PR).

2021-02-16 16:11 UTC, xvzcf commented on oqs-template/generate-oid-nid-table.py
> +    if kem['name_group'] == 'kyber512':
Sounds good. I'll update BoringSSL first and come back to this.

2021-02-16 20:10 UTC, baentsch approved these changes

2021-02-16 20:39 UTC, merged