Updates for Dilithium round 3
open-quantum-safe/openssl pull request #277
Opened 2021-02-05 13:05 UTC by bhess

* Updates OIDs for Dilithium round 3 (2, 3, 5, 2_aes, 3_aes, 5_aes)
* Updates security strengths
* Updates `mix_with` according to the security strengths
* `code_point` field is also updated to make the dilithium schemes fit consequently.

Addresses #276 

##### Checklist

- [x] documentation is added or updated
- [x] tests are added or updated

2021-02-05 13:13 UTC, baentsch commented on oqs-template/generate.yml
>                      'oid': '1.3.9999.2.2',
Please bump

2021-02-05 13:13 UTC, baentsch commented on oqs-template/generate.yml
>                      'oid': '1.3.9999.2.3',
same here

2021-02-05 13:13 UTC, baentsch commented on oqs-template/generate.yml
>                      'oid': '1.3.9999.2.6',
same

2021-02-05 13:16 UTC, baentsch requested changes
Please bump hybrid OIDs, too. Also, I don't understand why ` crypto/objects/obj_mac.num` gets _shorter_ with _more_ algorithms: Can you explain that?

2021-02-05 13:16 UTC, bhess commented on oqs-template/generate.yml
>                      'oid': '1.3.9999.2.2',
I wasn't completely sure about the implications of `code_point`. Should they rather not be changed?

2021-02-05 13:26 UTC, bhess commented
> Please bump hybrid OIDs, too. Also, I don't understand why ` crypto/objects/obj_mac.num` gets _shorter_ with _more_ algorithms: Can you explain that?

Thanks, updating them as well. Also checking the second one..

2021-02-05 13:55 UTC, bhess commented
> Also, I don't understand why ` crypto/objects/obj_mac.num` gets _shorter_ with _more_ algorithms: Can you explain that?

Hm, I don't see anything about kems being populated in the jinja-template: https://github.com/open-quantum-safe/openssl/blob/OQS-OpenSSL_1_1_1-stable/oqs-template/crypto/objects/obj_mac.num/assign_ids.fragment

The jinja-snipped might have been accidentally removed sometime.

2021-02-05 16:34 UTC, baentsch commented on oqs-test/test_tls_full.py
> +@pytest.fixture(params=["p384_dilithium3_aes"])
This doesn't look right.

2021-02-05 16:35 UTC, baentsch commented on oqs-template/generate.yml
>                      'oid': '1.3.9999.2.6',
also looks better with the latest commit

2021-02-05 16:38 UTC, baentsch commented
@xvzcf I'd be inclined to accept this PR (after the `test_tls_full` issue has been addressed) even though boring interop fails: Would you agree? Or in other words: Would you have time to look at updating boringssl? Or should @bhess or @baentsch look at that?

2021-02-05 16:44 UTC, xvzcf commented
> @xvzcf I'd be inclined to accept this PR (after the `test_tls_full` issue has been addressed) even though boring interop fails: Would you agree? Or in other words: Would you have time to look at updating boringssl? Or should @bhess or @baentsch look at that?

I'll try to update BoringSSL by the end of today and do at least one interop run, but if you or @bhess have spare cycles, I can review both this and the BoringSSL PR.

2021-02-05 16:45 UTC, xvzcf commented on oqs-test/test_tls_full.py
> +@pytest.fixture(params=["p384_dilithium3_aes"])
Indeed, this shouldn't have to be changed.

2021-02-05 16:48 UTC, bhess commented
Just opened a PR for BoringSSL:

https://github.com/open-quantum-safe/boringssl/pull/47

2021-02-05 16:51 UTC, bhess commented on oqs-template/generate.yml
>                      'oid': '1.3.9999.2.3',
done

2021-02-05 16:55 UTC, bhess commented on oqs-test/test_tls_full.py
> +@pytest.fixture(params=["p384_dilithium3_aes"])
good catch, let's hope that it still works now :)

2021-02-05 18:29 UTC, bhess commented
> > @xvzcf I'd be inclined to accept this PR (after the `test_tls_full` issue has been addressed) even though boring interop fails: Would you agree? Or in other words: Would you have time to look at updating boringssl? Or should @bhess or @baentsch look at that?
> 
> I'll try to update BoringSSL by the end of today and do at least one interop run, but if you or @bhess have spare cycles, I can review both this and the BoringSSL PR.

Marking this as ready. The hybrid OIDs are added in OpenSSL (BoringSSL seems to not to have any).
`crypto/objects/obj_mac.num` are fixed with an updated `assign_ids.fragment`. Interop-tests pass locally when pointing to the BoringSSL-PR.

2021-02-05 18:32 UTC, xvzcf commented
> The hybrid OIDs are added in OpenSSL (BoringSSL seems to not to have any).

Indeed, BoringSSL currently does not support hybrid signatures.

2021-02-07 11:44 UTC, baentsch approved these changes

2021-02-07 11:46 UTC, baentsch commented on crypto/objects/objects.txt
> +1 3 9999 3 11 4 : p521_dilithium5_aes : p521_dilithium5_aes
This is NOK: Falcon hybrid OID.

2021-02-07 11:48 UTC, baentsch requested changes
All other things now OK -- hybrid dil5_aes OID now in wrong OID space, though.

2021-02-07 11:48 UTC, baentsch commented on oqs-template/generate.yml
> +                    'oid': '1.3.9999.3.11.4',
This is origin of OID error. Please move hybrid dilithium5_aes to hybrid dilithium OID space

2021-02-08 08:43 UTC, bhess commented on oqs-template/generate.yml
> +                    'oid': '1.3.9999.3.11.4',
Thanks for spotting this! Moved to 1.3.9999.2.11.4

2021-02-08 08:54 UTC, bhess commented on crypto/objects/objects.txt
> +1 3 9999 3 11 4 : p521_dilithium5_aes : p521_dilithium5_aes
Updated, resolved in generate.yml

2021-02-08 10:47 UTC, baentsch approved these changes

2021-02-08 10:48 UTC, merged