Updated hybrid key format.
open-quantum-safe/openssl pull request #291
Opened 2021-03-09 20:59 UTC by xvzcf

2021-03-09 21:04 UTC, dstebila requested changes

2021-03-09 21:04 UTC, dstebila commented on ssl/statem/ext_oqs_extra.h
> +  EVP_PKEY* key = ssl_generate_pkey_group(NULL, ec_curve_id);
Do you need to free this before returning?

2021-03-09 21:04 UTC, dstebila commented on ssl/statem/ext_oqs_extra.h
> +  unsigned char *throwaway;
Do you need to free this before returning?

2021-03-09 21:07 UTC, xvzcf commented on ssl/statem/ext_oqs_extra.h
> +  unsigned char *throwaway;
Yes to both, I just put it up in the hopes someone would suggest a way without any of these allocations.

2021-03-09 21:09 UTC, dstebila commented on ssl/statem/ext_oqs_extra.h
> +  unsigned char *throwaway;
Not that I can think of, but I didn't check the EVP API to see if there's a function specifically for this purpose.  (You can probably get this information directly from crypto/ec, but that may pierce an abstraction layer that you don't want to...)

2021-03-09 21:16 UTC, xvzcf commented on ssl/statem/ext_oqs_extra.h
> +  unsigned char *throwaway;
@baentsch any ideas?

2021-03-10 06:50 UTC, baentsch commented on ssl/statem/ext_oqs_extra.h
> +  unsigned char *throwaway;
Sorry, not immediately: Getting a PKEY and then querying parameters (incl pub key len) is the only pattern I know using EVP ([also perpetuated in OSSL3](https://www.openssl.org/docs/manmaster/man3/EVP_PKEY_get1_encoded_public_key.html) as far as I can tell). Only by using EC APIs directly you may do other things (didn't look into that, though as I still don't like the "concept" OQS keys == EC keys :-) 

Second thought: Isn't there a classic PKEY object "around" (to use/query) anyway when doing hybrid operations? Shouldn't the SSL connection object contain a PKEY reference/or require building one during session setup) anyway? Why is there a need to create _this_ (new) throwaway object in the first place? A cursory glance at the `ssl/statem/extensions_clnt.c` lets me think there should be PKEY objects to query (and if a hybrid PKEY, why shouldn't that contain classic size information to query)?

2021-03-10 06:57 UTC, baentsch commented on ssl/statem/ext_oqs_extra.h
> +  *classical_msg_len = EVP_PKEY_get1_tls_encodedpoint(key, &throwaway);
The more I think about it, why not better create and use here a new `OQS_KEM_CLASSICAL_KEYLEN(<oqs-hybrid-group-id>) macro? If I'm not wrong, it only has three different alternative values to return...

2021-03-10 17:15 UTC, xvzcf commented on ssl/statem/ext_oqs_extra.h
> +  *classical_msg_len = EVP_PKEY_get1_tls_encodedpoint(key, &throwaway);
I ended up just doing this; we can make it a macro if we start finding that we need it in multiple places.

2021-03-11 15:54 UTC, dstebila approved these changes

2021-03-11 19:10 UTC, merged