adding ntrup1277
open-quantum-safe/openssl pull request #334
Opened 2021-10-19 10:11 UTC by baentsch

Enables S/NTRUP1277 as per https://github.com/open-quantum-safe/liboqs/pull/1111. ~CI should pass once this lands.~

- [x] documentation is added or updated
- [x] tests are added or updated

2021-10-24 20:20 UTC, dstebila requested changes
Also need to make sure the updated algorithm identifiers are recorded in [this table](https://github.com/open-quantum-safe/openssl/blob/OQS-OpenSSL_1_1_1-stable/oqs-template/oqs-kem-info.md).

2021-10-25 06:26 UTC, baentsch commented
> Also need to make sure the updated algorithm identifiers are recorded in [this table](https://github.com/open-quantum-safe/openssl/blob/OQS-OpenSSL_1_1_1-stable/oqs-template/oqs-kem-info.md).

Good catch! Wonder why this is not run automatically with rest of code generation. Will improve that.

2021-10-25 14:11 UTC, dstebila commented on oqs-template/oqs-kem-info.md
> +| NTRU-Prime     | supercop-20200826        | ntrulpr761      |            3 |                    1 | 0x2F30       | secp256_r1                       |
Why did this (and sntrup761) get downgraded to level 1?

2021-10-25 15:09 UTC, baentsch commented on oqs-template/oqs-kem-info.md
> +| NTRU-Prime     | supercop-20200826        | ntrulpr761      |            3 |                    1 | 0x2F30       | secp256_r1                       |
I don't know. Arguably a question to the NTRUPrime team. This is taken as-is from [PQClean](https://github.com/PQClean/PQClean/blob/7eb978b4a733696bd7197278aa84216095674524/crypto_kem/ntrulpr761/META.yml#L3) (NIST L2 maps to 128bits AFAIK). This is also documented in the same way in [liboqs](https://github.com/open-quantum-safe/liboqs/blob/main/docs/algorithms/kem/ntruprime.md#parameter-set-summary).

2021-10-25 17:48 UTC, dstebila commented on oqs-template/oqs-kem-info.md
> +| NTRU-Prime     | supercop-20200826        | ntrulpr761      |            3 |                    1 | 0x2F30       | secp256_r1                       |
Okay, that makes sense. But if we're switching from using p384 to p256 as the hybrid elliptic curve, shouldn't we bump the code point?

2021-10-26 05:38 UTC, baentsch commented on oqs-template/oqs-kem-info.md
> +| NTRU-Prime     | supercop-20200826        | ntrulpr761      |            3 |                    1 | 0x2F30       | secp256_r1                       |
That surely would ease the detection of interoperability problems with other PQ-hybrid-TLS implementations. Just wondering, though, is any other PQ-hybrid-enabling TLS apart from ours using the convention tying classic crypto algorithm (choice) to declared NIST strength for hybrid algs? 

The bigger issue I see is that within the "OQS universe" interoperability between 0.7.0 and 0.7.1 won't be achieved (i.e., already at `liboqs` level), so we need to bump `liboqs` to 0.8.0 just because of this classic/PQ combination automation. As we don't expect to guarantee 0.7/0.8 interop between OQS-TLS implementations, we _could_ retain code points.

Votes solicited: Bump code point or not? I really don't mind.

2021-10-26 14:07 UTC, dstebila commented on oqs-template/oqs-kem-info.md
> +| NTRU-Prime     | supercop-20200826        | ntrulpr761      |            3 |                    1 | 0x2F30       | secp256_r1                       |
> That surely would ease the detection of interoperability problems with other PQ-hybrid-TLS implementations. Just wondering, though, is any other PQ-hybrid-enabling TLS apart from ours using the convention tying classic crypto algorithm (choice) to declared NIST strength for hybrid algs?

I think s2n uses our table of code points, so they would.  I'm not aware of much else out there.

> The bigger issue I see is that within the "OQS universe" interoperability between 0.7.0 and 0.7.1 won't be achieved (i.e., already at `liboqs` level), so we need to bump `liboqs` to 0.8.0 just because of this classic/PQ combination automation. As we don't expect to guarantee 0.7/0.8 interop between OQS-TLS implementations, we _could_ retain code points.

Well liboqs versioning and TLS code points are somewhat separate issues.  

liboqs version bump from 0.7 to 0.8 is about whether a PQ algorithm in 0.7 has been updated in 0.8 in an incompatible way. As far as I know we haven't made any such changes yet since the liboqs 0.7 release.

TLS code points are also about compatibility -- TLS compatibility.  Any incompatible PQ algorithm change in liboqs would lead to a code point bump in TLS.  Although I don't believe we've encountered it before, changing the classical half of a hybrid would also mean TLS incompatibility, so would also merit a code point bump.

> Votes solicited: Bump code point or not? I really don't mind.

Yes.

2021-10-26 14:49 UTC, baentsch commented on oqs-template/oqs-kem-info.md
> +| NTRU-Prime     | supercop-20200826        | ntrulpr761      |            3 |                    1 | 0x2F30       | secp256_r1                       |
> liboqs version bump from 0.7 to 0.8 is about whether a PQ algorithm in 0.7 has been updated in 0.8 in an incompatible way. As far as I know we haven't made any such changes yet since the liboqs 0.7 release.

Oops - you're right of course: For some reason I was thinking hybrids are already supported in `liboqs`. They're clearly not, so my point above is moot.

> Yes.

So implemented now. Please check latest commit. Edit: BSSL interop expected to pass only when https://github.com/open-quantum-safe/boringssl/pull/78 has landed.

2021-10-26 15:27 UTC, dstebila approved these changes

2021-10-27 06:37 UTC, merged