Enable access to the curves and certificate type
open-quantum-safe/openssl pull request #426
Opened 2023-01-26 17:53 UTC by akihikokuroda

This PR changes enable access to the curves and certificate type used in TLSv1.1 handshakes.

This equivalent to access to the ciphers used in the TLS session. The benefit is that monitoring/logging can not only report the protocol and ciphers, but also the curve and certificate type used for a TLSv1.1 connection on the client side. In particular, an user can verify that a quantum-safe-crypto curve and certificate was used.

##### Checklist

- [ ] documentation is added or updated
- [ ] tests are added or updated

2023-01-26 18:52 UTC, baentsch commented
Thanks for this contribution! Your comment above confuses me a bit, though: The PR code does not look TLSv1.1 specific. Also, the OQS-enablement only works for TLSv1.3. Lastly, do you intend to add some example/test code, too?

2023-01-26 19:06 UTC, akihikokuroda commented
Oh, yes.  That's my mistake.  I meant V1.3.  I looked for the tests of `ssl3_ctrl` function but I couldn't.  Would you tell me where the other tests are.  I want to add tests for these functions.

2023-01-26 21:47 UTC, akihikokuroda commented
I'll try put some tests in test/sslapitest.c.  Is it the right place?

2023-01-27 06:24 UTC, baentsch commented on doc/man3/SSL_get_used_group_id.pod
> +SSL_get_used_group_nid() returns the name of the group of the curve that was used for the key agreement of the current TLS session establishment.
Strictly speaking this is not correct: This only returns the NID. You still have to run `OBJ_nid2sn` to get the (short) name.

2023-01-27 06:24 UTC, baentsch commented on doc/man3/SSL_get_used_group_id.pod
> +SSL_get_used_group_id() returns the ID of the group of the curve that was used for the key agreement of the current TLS session establishment.
Suggest to be precise: What is this ID (compared to the NID)?

2023-01-27 06:26 UTC, baentsch commented on doc/man3/SSL_get_used_group_id.pod
> +SSL_get_used_sigalg_nid() returns the name of the signature algorithm (and hash if applicable) that was used to sign the certificate of the peer.
Again, not the name. Also, why not return the (TLS spec) sig alg ID as in the group case? I think a use case (aka test) would clarify things.

2023-01-27 06:30 UTC, baentsch requested changes
Beyond the request for a test/usage example and the single comments just made, a general question/remark: At the core this looks like an OQS-independent mechanism enhancement: Have you considered contributing this to upstream OpenSSL?

2023-01-27 15:01 UTC, akihikokuroda commented
@baentsch Thanks for review.  I'll update the man page or the code.  I'm planing to work with the upstream OpenSSL in addition to OpenSSL V3 for both OQS and the upstream.

2023-02-01 23:39 UTC, Liamdruk commented
Hello, if you were into any investment or crypto scam. I will recommend and advice to reach out to The Recovery Agency, with no upfront fees, I recently got my money back.
Company Verified Telegram;https://t.me/TheRecovery_Agency

2023-02-01 23:40 UTC, Liamdruk commented
> Thanks for this contribution! Your comment above confuses me a bit, though: The PR code does not look TLSv1.1 specific. Also, the OQS-enablement only works for TLSv1.3. Lastly, do you intend to add some example/test code, too?

Hello, if you were into any investment or crypto scam. I will recommend and advice to reach out to The Recovery Agency, with no upfront fees, I recently got my money back.
Company Verified Telegram;https://t.me/TheRecovery_Agency

2023-02-09 06:10 UTC, baentsch commented on test/sslapitest.c
> +            || !TEST_long_eq(SSL_get_used_group_nid(serverssl), 1034)
What are these numbers (20, 1034)? Is there not a constant explaining each one? That should also make the code resilient to future code changes. I guess "0" in the below is NID_undef, right?

2023-02-09 06:10 UTC, baentsch commented on test/sslapitest.c
> +            || !TEST_long_eq(SSL_get_used_sigalg_nid(clientssl), 912))
What is 912?

2023-02-09 06:12 UTC, baentsch requested changes
Thanks for adding the test. Could you please use constants such as to make this "future proof"? Also, a test using an OQS algorithm would be good such as to ensure the added OQS logic gets tested, too.

2023-05-03 05:28 UTC, baentsch commented
@akihikokuroda Is this PR still something you'd like to move forward (and address the feedback) or shall we close this?

2023-05-03 11:48 UTC, akihikokuroda commented
Hi!  [V3 work](https://github.com/openssl/openssl/pull/20318) is moving forward, I close this.  Thanks for your help!

2023-05-03 11:48 UTC, closed without merging