Enable hybrid auth in TLS 1.3
open-quantum-safe/openssl pull request #62
Opened 2018-11-15 23:19 UTC by christianpaquin

*NOT READY FOR MERGE*: needs a few clean ups, more testing, and wiki documentation.

Enable hybrid auth in TLS 1.3 by defining naive hybrid schemes (parallel signatures; concatenated serialization of artifacts), combining p256/rsa3072 with L1 schemes, and p384 with L3 schemes.

##### Checklist

- [] address remaining TODOs
- [x] documentation is added or updated
- [ ] tests are added or updated

2018-11-20 01:34 UTC, christianpaquin commented
See updated [TLS 1.3 wiki](https://github.com/open-quantum-safe/openssl/wiki/PQC-integration-into-TLS-1.3) page

2018-11-20 19:38 UTC, christianpaquin commented
Need to fix an issue with OQS signature length before merging.

2018-11-20 22:03 UTC, christianpaquin commented
Fixed the issue, and refactored a few things. Ready for review, @dstebila.

2018-11-21 21:55 UTC, dstebila commented
Looks fine from visual inspection. I haven't run it yet.  Have you updated the OpenSSL integration testing script (https://github.com/open-quantum-safe/testing/blob/master/integration/oqs_openssl/run.sh) to exercise these new signature algorithms and successfully run that?

2018-11-22 19:55 UTC, christianpaquin commented
No I have not; the new sig schemes to test are: `p256_picnicL1FS`, `rsa3072_picnicL1FS`, `p256_qteslaI`, `rsa3072_qteslaI`, `p384_qteslaIIIsize`, and `p384_qteslaIIIspeed`

2018-11-26 21:58 UTC, christianpaquin commented
@dstebila, I added the hybrid sig algs to the testing project, see [PR10](https://github.com/open-quantum-safe/testing/pull/10).

2018-12-19 22:17 UTC, dstebila requested changes

2018-12-19 22:17 UTC, dstebila commented on crypto/ec/oqs_meth.c
>        ECerr(EC_F_OQS_PRIV_DECODE, EC_R_KEY_LENGTH_WRONG);
I'm getting a failure at this line (oqs\_meth.c, line 537) in some of the integration tests for the hybrid authentication algorithm `rsa3072_qteslaI`.  I've been able to reproduce as follows.  

1. Run `apps/openssl req -x509 -new -newkey rsa3072_qteslaI -keyout rq.key -out rq.crt -nodes -subj "/CN=oqstest" -days 365 -config apps/openssl.cnf`
2. Sometimes this will generate an `rq.key` file of 7391 bytes (~75% of the time?) and sometimes an `rq.key` file of 7395 bytes (~25% of the time?).
3. Run `apps/openssl s_server -cert rq.crt -key rq.key -www -tls1_3`.  When using the 7391-byte file, it works fine.  When using the 7395-byte file, it fails with the following error:

```
unable to load server certificate private key file
139704744150784:error:1012A0A9:elliptic curve routines:oqs_priv_decode:key length wrong:crypto/ec/oqs_meth.c:537:
139704744150784:error:0606F091:digital envelope routines:EVP_PKCS82PKEY:private key decode error:crypto/evp/evp_pkey.c:44:
139704744150784:error:0907B00D:PEM routines:PEM_read_bio_PrivateKey:ASN1 lib:crypto/pem/pem_pkey.c:88:
```

2018-12-19 22:21 UTC, dstebila commented
FYI you can now use the updated open-quantum-safe/testing#10 to run integration tests, just edit lines 20 and 21 to read:

```
OPENSSL_111_REPO="https://github.com/christianpaquin/openssl.git"
OPENSSL_111_BRANCH="cp-hybrid-sig"
```

2018-12-19 22:40 UTC, christianpaquin commented
I'll take a look

2018-12-20 16:49 UTC, christianpaquin commented on crypto/ec/oqs_meth.c
>        ECerr(EC_F_OQS_PRIV_DECODE, EC_R_KEY_LENGTH_WRONG);
Seems that RSA key size were sometimes larger than expected; I increased the max size accordingly, and added more tests to avoid generating keys (should not happen anymore) that can't be parsed.

2018-12-20 18:14 UTC, dstebila approved these changes

2018-12-20 18:15 UTC, dstebila commented
Integration tests passed for me on Ubuntu 16.04.

2018-12-20 18:15 UTC, merged